version: "3"
services:
#  Container for Java
#  docker run -d --name track-service-java -network host spring-boot-java
  java:
    build: .
    container_name: track-service-java
    network_mode: "host"
#  Container for Mongo
# docker run -d --name track-service-mongo -network host mongo
  mongo:
    image: mongo
    container_name: track-service-mongo
    network_mode: "host"
